module.exports = {
    MIN_NUMBER_OF_ARMIES: 2,
    MIN_NUMBER_OF_SQUADS_PER_ARMY: 2,
    MIN_NUMBER_OF_UNITS_PER_SQUAD: 5,
    MAX_NUMBER_OF_UNITS_PER_SQUAD: 10,
    MIN_NUMBER_OF_SOLDIERS_PER_VEHICLE: 1,
    MAX_NUMBER_OF_SOLDIERS_PER_VEHICLE: 3,
    VEHICLE_DAMAGE_INTAKE : 0.3,
    MAIN_SOLDIER_DAMAGE_INTAKE : 0.5,
    OTHER_SOLDIERS_DAMAGE_INTAKE : 0.2,
    VEHICLE_MIN_DAMAGE : 0.1,
    VEHICLE_OPERATOR_XP_NORMALIZER : 100.0,
    VEHICLE_HEALTH_NORMALIZER : 100.0,
    VEHICLE_ATTACK_PONDER : 0.5,
    SOLDIER_HEALTH_NORMALIZER : 100.0,
    SOLDIER_EXP_NORMALIZER : 100.0,
    SOLIDER_ATTACK_MIN_EXP_GAIN : 30.0,
    SOLDIER_ATTACK_MAX_EXP_GAIN : 100.0,
    SOLDIER_ATTACK_PONDER : 0.5,
    SOLDIER_MIN_DAMAGE : 0.05,
    SOLDIER_DAMAGE_EXP_PONDER: 100.0,
    MAX_EXPERIENCE_PER_SOLDIER: 50

}